In [5]:
import torch

# Example tensor list
tensor_list = [
    torch.tensor([[1, 2, 3], [8, 7, 5]]),  # 2D tensor
    torch.tensor([[4, 5, 6]]),              # 1D tensor
    torch.tensor([[7, 8, 9]])               # 1D tensor
]

In [6]:
tensor_list

[tensor([[1, 2, 3],
         [8, 7, 5]]),
 tensor([[4, 5, 6]]),
 tensor([[7, 8, 9]])]

In [7]:
torch.cat(tensor_list)

tensor([[1, 2, 3],
        [8, 7, 5],
        [4, 5, 6],
        [7, 8, 9]])

In [8]:
torch.cat(tensor_list).tolist()

[[1, 2, 3], [8, 7, 5], [4, 5, 6], [7, 8, 9]]